# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Api-Tools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Api-Tools
  pod 'PrismaApiRouter', :path => '../'
  

  target 'Api-ToolsTests' do
    pod 'PrismaApiRouter', :path => '../'
  end
  
end
